stages:
  - test
  - deploy_dev
  - deploy_test
  - deploy_trs

test:
  image: python:3.6
  stage: test
  allow_failure: false
  before_script:
    - apt-get -qq update
    - apt-get -qq install -y python-virtualenv python3-pip
    - python3 -m venv test_environment
    - . test_environment/bin/activate
    - export SHIR_CONNECT_ENV=TEST
    - export REACT_APP_SHIR_CONNECT_CONFIG=trs
  script:
    - echo $SHIR_CONNECT_ENV
    - echo "${POSTGRES_HOST}:5432:*:master:${POSTGRES_PASSWORD}" >> ~/.pgpass
    - chmod 0600 ~/.pgpass
    - cd server
    - pip install -e .[test]
    - shir_connect initialize --drop_views
    - py.test --cov=shir_connect
  coverage: '/TOTAL.*\s+(\d+%)$/'

deploy_dev:
  stage: deploy_dev
  image: ubuntu:latest
  when: manual
  before_script:
    - sh scripts/ci_deploy_setup.sh
    - export NVM_DIR="/root/.nvm"
    - source $HOME/.nvm/nvm.sh
    - nvm install node
    - nvm install 11.0.0
    - nvm use 11.0.0
    - export REACT_APP_SHIR_CONNECT_CONFIG=trs
    - export SHIR_CONNECT_ENV=DEV
  script:
    - cd ui
    - npm install
    - npm run build
    - cd ../deployment
    - ansible-playbook -i $HOME/hosts deploy.yml -e host=shir_connect -e user=ubuntu -e branch=$CI_COMMIT_SHA -e project_dir=$CI_PROJECT_DIR -e subdomain=dev

deploy_test:
  stage: deploy_test
  image: ubuntu:latest
  when: manual
  only:
    - master
  before_script:
    - sh scripts/ci_deploy_setup.sh
    - export NVM_DIR="/root/.nvm"
    - source $HOME/.nvm/nvm.sh
    - nvm install node
    - nvm install 11.0.0
    - nvm use 11.0.0
    - export REACT_APP_SHIR_CONNECT_CONFIG=trs
    - export SHIR_CONNECT_ENV=TEST
  script:
    - cd ui
    - npm install
    - npm run build
    - cd ../deployment
    - ansible-playbook -i $HOME/hosts deploy.yml -e host=shir_connect -e user=ubuntu -e branch=$CI_COMMIT_SHA -e project_dir=$CI_PROJECT_DIR -e subdomain=test

deploy_demo:
  stage: deploy_test
  image: ubuntu:latest
  when: manual
  only:
    - master
  before_script:
    - sh scripts/ci_deploy_setup.sh
    - export NVM_DIR="/root/.nvm"
    - source $HOME/.nvm/nvm.sh
    - nvm install node
    - nvm install 11.0.0
    - nvm use 11.0.0
    - export REACT_APP_SHIR_CONNECT_CONFIG=demo
    - export SHIR_CONNECT_ENV=PROD
  script:
    - cd ui
    - npm install
    - npm run build
    - cd ../deployment
    - ansible-playbook -i $HOME/hosts deploy.yml -e host=shir_connect -e user=ubuntu -e branch=$CI_COMMIT_SHA -e project_dir=$CI_PROJECT_DIR -e subdomain=demo

deploy_trs:
  stage: deploy_trs
  image: ubuntu:latest
  only:
    - tags
  when: manual
  before_script:
    - sh scripts/ci_deploy_setup.sh
    - export NVM_DIR="/root/.nvm"
    - source $HOME/.nvm/nvm.sh
    - nvm install node
    - nvm install 11.0.0
    - nvm use 11.0.0
    - export REACT_APP_SHIR_CONNECT_CONFIG=trs
    - export SHIR_CONNECT_ENV=PROD
  script:
    - cd ui
    - npm install
    - npm run build
    - cd ../deployment
    - ansible-playbook -i $HOME/hosts deploy.yml -e host=shir_connect -e user=ubuntu -e branch=$CI_COMMIT_TAG -e project_dir=$CI_PROJECT_DIR -e subdomain=trs
