stages:
  - test
  - deploy_dev

test:
  image: python:3.6
  stage: test
  before_script:
    - apt-get -qq update
    - apt-get -qq install -y python-virtualenv python3-pip
    - python3 -m venv test_environment
    - . test_environment/bin/activate
  script:
    - pwd
    - echo $SHIR_CONNECT_ENV
    - echo "13.58.50.14:5432:*:postgres:${POSTGRES_PASSWORD}" >> ~/.pgpass
    - chmod 0600 ~/.pgpass
    - cd server
    - pip install -e .[test]
    - py.test --cov=shir_connect
  coverage: '/TOTAL.*\s+(\d+%)$/'

deploy_dev:
  stage: deploy_dev
  image: ubuntu:latest
  when: manual
  before_script:
    # Install open ssh and add remote server to known hosts
    - apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*
    - apt-get update && sudo apt-get install -y openssh-server
    - mkdir -p $HOME/.ssh
    - echo "$SSH_PRIVATE" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 0600 $HOME/.ssh/id_rsa
    - echo $SSH_PUBLIC >> $HOME/.ssh/id_rsa.pub
    - chmod 0600 $HOME/.ssh/id_rsa.pub
    - ssh-agent bash -s
    - ssh-keyscan -H 13.58.50.14 >> $HOME/.ssh/known_hosts

    # Install NVM and NPM
    - sudo apt-get update && sudo apt-get -y install curl
    - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
    - export NVM_DIR="/root/.nvm"
    - source $HOME/.nvm/nvm.sh
    - nvm install node
    - nvm install 11.0.0
    - nvm use 11.0.0

    # Install Ansible
    - sudo apt-get update
    - sudo apt-get -y install software-properties-common
    - sudo apt-add-repository --yes --update ppa:ansible/ansible
    - sudo apt-get -y install ansible
    - echo "[dev]" >> $HOME/hosts
    - echo "ubuntu@13.58.50.14" >> $HOME/hosts
  script:
    - cd ui
    - npm install
    - npm run build
    - cd ../deployment
    - ansible-playbook -i $HOME/hosts deploy.yml -e host=dev -e user=ubuntu -e local_user=ubuntu -e $CI_COMMIT_SHA
