test:
  before_script:
    - apt-get -qq update && apt-get -qq install -y python
    - apt-get -qq update
    - apt-get -qq install -y python python-virtualenv python-pip
    - virtualenv venv
    - . venv/bin/activate
  script:
    - echo "13.58.50.14:5432:*:postgres:$POSTGRES_PASSWORD" >> ~/.pgpass
    - cd server
    - pip install -e .
    - py.test --cov=shir_connect
