test:
  image: python:3.6
  before_script:
    - apt-get -qq update
    - apt-get -qq install -y python-virtualenv python3-pip
    - python3 -m venv test_environment
    - . test_environment/bin/activate
  script:
    - echo "13.58.50.14:5432:*:postgres:$POSTGRES_PASSWORD" >> ~/.pgpass
    - chmod 0600 ~/.pgass
    - cd server
    - pip install -e .[test]
    - py.test --cov=shir_connect
