---
- hosts: "{{ host }}"
  become_user: "{{ user }}"
  vars:
    path: "$HOME"
    node_version: "{{ node_version }}"
    shir_connect: "{{ path }}/{{ subdomain }}/shir-connect"
    project_dir: "{{ project_dir }}"
  tasks:
    - name: Stopping all running PM2 processes
      shell: 'bash -ic "pm2 stop all"'
    
    - name: Remove current UI build
      file:
        path: "{{ shir_connect }}/ui/build"
        state: absent

    - name: Transferring updated UI build
      copy:
        src: "{{ project_dir }}/ui/build"
        dest: "{{ shir_connect }}/ui/"

    - name: Pull the latest code from GitLab
      git:
        repo: git@gitlab.com:fiddler-analytics/shir-connect.git
        version: "{{ branch }}"
        dest: "{{ shir_connect }}"
        update: yes
    
    - name: Install new Python dependencies
      shell: "{{ path }}/venv/shir_connect/bin/pip install -e ."
      args:
        chdir: "{{ shir_connect }}/server"

    - name: Run database mirgrations
      shell: "shmig -t postgresql -d postgres up"
      args:
        chdir: "{{ shir_connect }}/database"

    - name: Update materialized views
      shell: "{{ path }}/venv/shir_connect/bin/shir_connect initialize --drop_views"


    - name: Restarting all PM2 processes
      shell: 'bash -ic "pm2 start all"'
