---
- hosts: "{{ host }}"
  become_user: "{{ user }}"
  vars:
    node_version: "{{ node_version }}"
    shir_connect: "$HOME/{{ subdomain }}/shir_connect"
    project_dir: "{{ project_dir }}"
    venv: "$HOME/venv/{{ subdomain }}/bin"
  tasks:
    - name: Stopping all running PM2 backend processes
      shell: 'bash -ic "pm2 stop {{ subdomain }}_rest"'
    
    - name: Stopping all running PM2 frontend processes
      shell: 'bash -ic "pm2 stop {{ subdomain }}_ui"'
    
    - name: Remove current UI build
      file:
        path: "{{ shir_connect }}/ui/build"
        state: absent

    - name: Transferring updated UI build
      copy:
        src: "{{ project_dir }}/ui/build"
        dest: "{{ shir_connect }}/ui/"

    - name: Pull the latest code from GitLab
      git:
        repo: git@gitlab.com:fiddler-analytics/shir-connect.git
        version: "{{ branch }}"
        dest: "{{ shir_connect }}"
        update: yes
    
    - name: Install new Python dependencies
      shell: "{{ venv }}/pip install -e ."
      args:
        chdir: "{{ shir_connect }}/server"

    - name: Run database mirgrations
      shell: "shmig -t postgresql -d {{ subdomain }} up"
      args:
        chdir: "{{ shir_connect }}/database"

    - name: Update materialized views
      shell: "{{ venv }}/shir_connect initialize --drop_views"

    - name: Starting PM2 backend processes
      shell: 'bash -ic "pm2 start {{ subdomain }}_rest"'
    
    - name: Starting PM2 frontend processes
      shell: 'bash -ic "pm2 start {{ subdomain }}_ui"'
