---
- hosts: "{{ host }}"
  become: yes
  tasks:
    - name: Add postgres key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add postgres apt repo
      shell: sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -sc)-pgdg main" > /etc/apt/sources.list.d/PostgreSQL.list'

    - name: Download nginx key
      apt_key: 
        url: http://nginx.org/keys/nginx_signing.key
        state: present

    - name: Install Lets Encrypt repo
      shell: "add-apt-repository -y ppa:certbot/certbot"

    - name: Update apt-cache
      apt:
        update_cache: yes

    - name: Install base packages
      apt: 
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - postgresql-10
          - nginx
          - python-pip
          - python3-venv
          - software-properties-common
          - python-certbot-nginx

    - name: Install NVM
      become_user: ubuntu
      shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash

    - name: Add NVM environment to .bashrc
      become_user: ubuntu
      shell: echo export NVM_DIR="/root/.nvm" > $HOME/.bashrc 
    
    - name: Source NVM in .bashrc
      become_user: ubuntu
      shell: echo "source $HOME/.nvm/nvm.sh" >> $HOME/.bashrc

    - name: Install node
      become_user: ubuntu
      shell:  export NVM_DIR="/home/ubuntu/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . $NVM_DIR/nvm.sh && nvm install node && nvm install --lts && nvm use --lts

    - name: Install PM2 and node server
      become_user: ubuntu
      shell: export NVM_DIR="/home/ubuntu/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . $NVM_DIR/nvm.sh && npm install -g serve pm2

    - name: Update postgres password
      become_user: postgres
      shell: psql -U postgres -d postgres -c "alter user postgres with password '{{ password }}';"

    - name: Setup .pgpass file
      become_user: ubuntu
      shell: echo "localhost:5432:*:postgres:{{ password }}" > $HOME/.pgpass

    - name: Set permissions on .pgpass file
      become_user: ubuntu
      shell: chmod 0600 $HOME/.pgpass
