name: Temple Rodef Shalom

subdomain: dev

modules:
  - events
  - members
  - trends
  - map
  - report

location:
  name: Temple Rodef Shalom
  address_1: "2100 Westmoreland Street"
  address_2: null
  city: Falls Church
  region: VA
  country: US
  latitude: 38.906111
  longitude: -77.173588
  postal_code: 22043

event_groups:
  - Food 4 Thought
  - TRSNS
  - Rodef 2100
  - WoTRS
  - Parent Workshop
  - Renaissance
  - Feed Em Friday
  - Lox and Lecture
  - Tot Shabbat
  - TRS Tents

map_event_options:
  - Rodef 2100
  - WoTRS
  - Renaissance
  - TRS Tents
  - TRSTY

member_types:
  MEMFAM: Family
  MEMIND: Individual
  STAFF: Staff
  MEMYNG: Young Prof.
  JCCMEM: JCC

age_groups:
  18-22:
    min: 18
    max: 23
  22-35:
    min: 23
    max: 35
  35-50:
    min: 35
    max: 50
  50-60:
    min: 50
    max: 60
  60-70:
    min: 60
    max: 70
  70-80:
    min: 70
    max: 80
  Over 80:
    min: 80
